spring.application.name=ollama
server.port=8088

# DeepSeek API配置
deepseek.api.key=sk-2095e4a02a5a4b3d84c2150ce62a67b7
deepseek.api.url=https://api.deepseek.com/v1/chat/completions
deepseek.model=deepseek-chat

# 历史记录文件路径
chat.history.path=./data/chat_history.json
# 聊天记忆文件路径
chat.memory.path=./data/chat_memory.json